import { chromium } from '/home/ubuntu/node_modules/playwright/index.mjs';

const browser = await chromium.launch({headless: true});
const page = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true });
await page.goto('http://127.0.0.1:4173/v2/', { waitUntil: 'networkidle' });
await page.screenshot({ path: '/home/ubuntu/MARBS-GYM/relatorios/v2-captura-local.png', fullPage: true });
if (!(await page.locator('[data-screen="home"] h1').textContent()).includes('Bom dia')) throw new Error('home não abriu');
await page.getByRole('button', { name: /Iniciar treino/i }).click();
if (!(await page.locator('[data-screen="focus"]').isVisible())) throw new Error('treino guiado não abriu');
const tableOverflow = await page.locator('[data-screen="focus"] .table-wrap').evaluate(el => el.scrollWidth > el.clientWidth + 1);
if (tableOverflow) throw new Error('tabela de séries ainda exige rolagem horizontal');
await page.screenshot({ path: '/home/ubuntu/MARBS-GYM/relatorios/v2-treino-compacto-local.png', fullPage: true });
await page.getByRole('button', { name: /Usar último treino/i }).click();
if (!(await page.getByRole('dialog', { name: /Usar dados do último treino/i }).isVisible())) throw new Error('modal de cópia não abriu');
await page.getByRole('button', { name: 'Cancelar' }).click();
await page.locator('input[data-field="done"]').first().check();
await page.getByRole('button', { name: /Concluir exercício/i }).click();
if (!(await page.getByRole('dialog', { name: /Como foi esta atividade/i }).isVisible())) throw new Error('modal de esforço não abriu');
await page.getByRole('button', { name: '8' }).click();
await page.getByRole('button', { name: /Salvar e continuar/i }).click();
await page.getByRole('button', { name: 'Progresso' }).click();
if (!(await page.locator('[data-screen="progress"] h1').textContent()).includes('Progresso')) throw new Error('progresso não abriu');
await page.getByRole('button', { name: 'Dieta' }).click();
if (!(await page.locator('[data-screen="diet"] h1').textContent()).includes('Dieta')) throw new Error('dieta não abriu');
await page.getByRole('button', { name: 'Hoje', exact: true }).click();
await page.locator('[data-screen="home"]').waitFor({ state: 'visible' });
await page.locator('[data-screen="home"] [data-screen-link="library"]').click();
if (!(await page.locator('[data-screen="library"] h1').textContent()).includes('Biblioteca')) throw new Error('biblioteca não abriu');
await page.getByRole('button', { name: 'Calculadora' }).click();
if (!(await page.locator('[data-screen="calculator"] h1').textContent()).includes('Calculadora')) throw new Error('calculadora não abriu');
await page.getByRole('button', { name: 'Hoje', exact: true }).click();
await page.getByRole('button', { name: /Abrir menu/i }).click();
await page.locator('[data-screen-link="settings"]').click();
if (!(await page.locator('[data-screen="settings"] h1').textContent()).includes('Configurações')) throw new Error('configurações não abriu');
await browser.close();
console.log('v2-browser-check: ok');
